site_name: MSU Cloud Fellowship
nav:
    - Home: index.md
    - Outline:
      - 1. Introduction: session-introduction/index.md
      - 2. How does the cloud work?: session_how_to_cloud/index.md
    - People: people.md 
theme: 
  name: material
  palette:
    primary: black
