site_name: MSU Cloud Fellowship
nav:
    - Home: index.md
    - Sessions:
      - 1. Introduction: session_introduction
      - 2. How does the cloud work?: session_how_to_cloud
      - 3. Cloud Storage: session_cloud_storage
    - About Us: people.md 
    - Contact: contact.md
    - References: references
theme: 
  name: material
  features:
    - navigation.sections
  palette:
    primary: black
markdown_extensions:
  - attr_list